### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by petrparolek** [webnazakazku/Library-IS#2]
front:
* [ ] seznam dostupných autorů, knih a svazků´
* [ ]  seznam vypůjčených knih

admin
* [x] seznam a správa autorů
* [x] seznam a správa knih
* [ ] seznam a správa svazků
* [ ] seznam a správa uživatelů (adminů a čtenářů)
